### ISSUE TITLE
Compiltatio problem with esphome 2023.4.0 

### ISSUE THREAD

**Issue by ivhercla** [arthurrump/esphome-opentherm#17]
There is a problem when i try to compil.  

THNKS 

******
INFO Reading configuration /config/esphome/d1_mini_2.yaml...
WARNING 'd1_mini_2': Using the '_' (underscore) character in the hostname is discouraged as it can cause problems with some DHCP and local name services. For more information, see https://esphome.io/guides/faq.html#why-shouldn-t-i-use-underscores-in-my-device-name
INFO Generating C++ source...
Traceback (most recent call last):
  File "/usr/local/bin/esphome", line 33, in <module>
    sys.exit(load_entry_point('esphome', 'console_scripts', 'esphome')())
  File "/esphome/esphome/__main__.py", line 965, in main
    return run_esphome(sys.argv)
  File "/esphome/esphome/__main__.py", line 952, in run_esphome
    rc = POST_CONFIG_ACTIONS[args.command](args, config)
  File "/esphome/esphome/__main__.py", line 397, in command_run
    exit_code = write_cpp(config)
  File "/esphome/esphome/__main__.py", line 178, in write_cpp
    generate_cpp_contents(config)
  File "/esphome/esphome/__main__.py", line 190, in generate_cpp_contents
    CORE.flush_tasks()
  File "/esphome/esphome/core/__init__.py", line 622, in flush_tasks
    self.event_loop.flush_tasks()
  File "/esphome/esphome/coroutine.py", line 246, in flush_tasks
    next(task.iterator)
  File "/esphome/esphome/__main__.py", line 170, in wrapped
    await coro(conf)
  File "/config/esphome/.esphome/external_components/d4d3a138/components/opentherm/number.py", line 34, in to_code
    keys = await generate.component_to_code(
  File "/config/esphome/.esphome/external_components/d4d3a138/components/opentherm/generate.py", line 107, in component_to_code
    entity = await create(conf, key, hub)
  File "/config/esphome/.esphome/external_components/d4d3a138/components/opentherm/number.py", line 18, in new_openthermnumber
    await number.register_number(var, config, min_value = config[input.CONF_min_value], max_value = config[input.CONF_max_value])
TypeError: register_number() missing 1 required keyword-only argument: 'step'

**Comment by Xekz** [comment]
how compile?

**Comment by cadavre** [comment]
Fix for this is available under #15 .

Before it is merged you can use temporary @ov1d1u repository:

```
external_components:
  source: github://ov1d1u/esphome-opentherm@main
```
