### ISSUE TITLE
ESPHome error when using number input

### ISSUE THREAD

**Issue by wildekek** [arthurrump/esphome-opentherm#21]
ESPHome config
```
number:
  - platform: opentherm
    t_dhw_set:
      name: "Boiler DHW Setpoint"
    max_t_set:
      name: "Boiler Max Setpoint"
```

ESPHome output

```
INFO ESPHome 2023.10.0
INFO Reading configuration /config/esphome/heating-controller.yaml...
INFO Generating C++ source...
Traceback (most recent call last):
  File "/usr/local/bin/esphome", line 33, in <module>
    sys.exit(load_entry_point('esphome', 'console_scripts', 'esphome')())
  File "/esphome/esphome/__main__.py", line 1036, in main
    return run_esphome(sys.argv)
  File "/esphome/esphome/__main__.py", line 1023, in run_esphome
    rc = POST_CONFIG_ACTIONS[args.command](args, config)
  File "/esphome/esphome/__main__.py", line 454, in command_run
    exit_code = write_cpp(config)
  File "/esphome/esphome/__main__.py", line 189, in write_cpp
    generate_cpp_contents(config)
  File "/esphome/esphome/__main__.py", line 201, in generate_cpp_contents
    CORE.flush_tasks()
  File "/esphome/esphome/core/__init__.py", line 650, in flush_tasks
    self.event_loop.flush_tasks()
  File "/esphome/esphome/coroutine.py", line 246, in flush_tasks
    next(task.iterator)
  File "/esphome/esphome/__main__.py", line 181, in wrapped
    await coro(conf)
  File "/data/external_components/f21ab308/components/opentherm/number.py", line 34, in to_code
    keys = await generate.component_to_code(
  File "/data/external_components/f21ab308/components/opentherm/generate.py", line 107, in component_to_code
    entity = await create(conf, key, hub)
  File "/data/external_components/f21ab308/components/opentherm/number.py", line 18, in new_openthermnumber
    await number.register_number(var, config, min_value = config[input.CONF_min_value], max_value = config[input.CONF_max_value])
TypeError: register_number() missing 1 required keyword-only argument: 'step'
```

**Comment by wildekek** [comment]
Fixed by https://github.com/arthurrump/esphome-opentherm/pull/15
